### ISSUE TITLE
[Config] Save to Disk Toggle

### ISSUE THREAD

**Issue by pvienneau** [pvienneau/atom-template-json#1]
As per @sartian's proposal, implement toggle switch in package settings to control if a file gets saved to disk or not.

**Default**: `true`
1. If `true`:
    - File should be open as a tab in the editor.
    - File should be saved to disk, bearing same filename as `.template.json` file, with updated `.json` extension.
    - File should be saved inside same directory as related `.template.json` file.
    - Tab should be set to active.
2. If `false`:
    - File should be open as a tab in the editor.
    - File should be bearing the same filename as `.template.json` file, with updated `.json` extension.
    - Tab should be set to active.

**Comment by pvienneau** [comment]
Resolved as part of release [0.0.8](https://github.com/pvienneau/atom-template-json/releases/tag/v0.0.8).

**Comment by sartian** [comment]
Wow, thanks!
